### PR TITLE
Slight Signpost refactor and slight Muse mayo

### PR DESCRIPTION
**Pull request by Calamitizer**
Using .Level for signpost activation was causing weird buying effects, so I switched it. Also, Muse now has a correct description if you're somehow reading it while Muse is locked (like favorites). However, #1332 is not fully resolved.

### CODE REVIEW

**Comment by Calamitizer** [comment]
Hey @pickten - I reverted my changes to the RewardOptions because I thought I had broken QQs, but after reverting and messing around, I think there was a problem before. QQs were throwing exceptions. Changing a .indexof() to .indexOf() removed the exceptions and caused QQ/Mario to unlock ASHF again, but neither is opening Vaults for me. I think it might have to do with the same line: ```!string.indexOf(item)``` is probably not the boolean you're looking for, since ```-1 == true``` and ```0 == false``` (and JS starts indexing at 0). But I fiddled around with it, and couldn't fix QQs - so could you check and make sure you can still open LVs?

**Comment by pickten** [comment]
Damn. I thought it worked before. Rechecking.

**Comment by Calamitizer** [comment]
Ah, damn. I'm sitting with Mario on, Rob buying vaults and keys, and watching the LV stats screen, and nothing's happening. Is it on my end, then? I hadn't thought I'd ever changed logicat code before this merge but maybe I'm wrong.

Side note: Where they are now, ```Molpy.LogicatRewardOptions``` et al. cause intermittent crashing (when ```Molpy.RewardLogicat()``` gets called before ```Molpy.LogicatRewardOptions``` gets a chance to be defined, something to do with whether you load or import and your save options or something). I'm also not really sure where they should go, but putting them immediately before ```Molpy.RewardLogicat()``` seems to work for now.

**Comment by Calamitizer** [comment]
I think the location of ```Molpy.LogicatRewardOptions``` maybe what's causing the problem for me... but figuring out where to put it is a fresh hell, for whatever reason. I can't find somewhere that looks reasonable and is posterior in scope to both ```Molpy.Boosts``` being populated and ```Molpy.BoostsByFunction``` being defined. Sigh.

**Comment by Calamitizer** [comment]
Okay, I have written ```Molpy.BuildRewardsList()```, which prevents the scope-related crashing (and ```Molpy.LogicatRewardOptions``` sometimes returning an empty array). It remains to be seen whether I can figure out why I'm not opening any vaults (or unlocking ASHF, come to think of it).

**Comment by Calamitizer** [comment]
I think I have found the problem for vaults: it's inside ```Molpy.UnlockRepeatableBoosts```. In the block

```
var RobbySee=Molpy.Boosts['Rob'];
var RobbyDo=[];
for(var thingy = 0; thingy <= RobbySee.bought; thingy++) {
	var item = Molpy.BoostsById[thingy + 1];
	if(item.power) {
	RobbyDo.push(item.alias)
	}
}
```

RobbyDo ends up being wonky things. For me it ends up being ```["Huge Buckets", "Helping Hand", "Cooperation", "Spring Fling"]```. If I hardcode-jumpstart ```var RobbyDo = ['Vault Key']```, vault key autobuy starts working again and I start opening vaults. Actually, with this problem in mind, it's odd that Locked Vaults themselves autobuy, isn't it? Anyway, I hope this helps you figure out what's going on. I'm going to work on other stuff for a while.

**Comment by pickten** [comment]
Wow, OK. That's very helpful. I didn't have time to check anything (no internet connection for the last 3 days), but that makes sense, since most of the rest of the code for repeatable is copied from the original boost funcs. I think what's happening is that, rather than take the targets, it's getting the default for some reason, in which case i probably misunderstood the original code.

**Pull request merged**
