### PR TITLE
Undo the undo of a 2016 PR 

### PR DESCRIPTION
**Pull request by IHaveNoFunnyName**
Sorry about the mess. I probably should have deleted the fork and started clean rather than try and salvage it. 

Full story because I think it's funny:

I started working on a bugfix and noticed that old code from that PR was in my master. I pulled upstream/master but that merged it rather than overwriting, so it didn't really help. Frustrated I made a new branch from upstream/master, but just before I did so, entirely coincidentally, the 2016 PR was merged, so the old code was _still_ in my branch. (idk why i'm writing passively here, it's not like anyone other than ED is going to read this). Completely freaked out and presuming it was a git bug at this point (the corruption in options.js didn't help) I manually undid the commits before fixing the bug. Which then undid the origional PR when it was merged too.

### CODE REVIEW

**Comment by IHaveNoFunnyName** [comment]
oh look i made the same mistake again and this PR is from master

**Comment by eternaldensity** [comment]
Um so is this a PR I should merge or shouldn't merge?

**Comment by IHaveNoFunnyName** [comment]
Should be merged. #1516 contains commits that undo #1443, and this fixes that.

**Comment by eternaldensity** [comment]
ah, got it, thanks.

**Comment by Calamitizer** [comment]
> _idk why i'm writing passively here, it's not like anyone other than ED is going to read this_

Don't tell me how to live my life! =P

**Pull request merged**
