### PR TITLE
Update to 3.67

### PR DESCRIPTION
**Pull request by LuminousLeopards**
All ready to go

### CODE REVIEW

**Comment by eternaldensity** [comment]
Excellent, I was thinking of doing some testing and a release soon :D

**Comment by LuminousLeopards** [comment]
Cool cool, I've done a fair amount of testing already but more is always better. I do have a post written up for when it goes live--if you prefer to post it I can PM it to you.

**Comment by eternaldensity** [comment]
I'm prepared to go live, and I'm fine with you being the one to post on Reddit.  The tricky part is whether/when you are online to do so.

**Comment by LuminousLeopards** [comment]
I'll be online for the next 18 hours or so.

**Comment by eternaldensity** [comment]
Going now...

**Comment by eternaldensity** [comment]
And live!

**Comment by LuminousLeopards** [comment]
Sorry, was playing Witcher 3. My post is up now if you'd care to sticky it.

**Comment by eternaldensity** [comment]
Excellent, and no problem.

**Pull request merged**
