### PR TITLE
"Finish" Sokoban

### PR DESCRIPTION
**Pull request by pickten**
As noted in #1442, this has a few tiny lingering things to be done, but those are things I'd like input on and are extremely quick (in the case of the optimization, I've even written the relevant code to swap in if that's wanted).

### CODE REVIEW

**Comment by Calamitizer** [comment]
Cool! I'll try to get a chance to check this out sometime next week (spring break). I developed loads of Moon Spire content every day for about two weeks then got completely slammed with schoolwork for the past like month, eheh. I've got about four open projects presently and it doesn't seem like it'll slow down before the end of the semester, so further Moon Spire development on my end will probably have to wait till the summer. I'll still try to at least check out this push and offer feedback sometime soon, though. Great job!

**Comment by pickten** [comment]
Yeah, I went to look at your repo the other day to see if you'd already set up some sort of `Molpy.Sokoban.complete` (what a finished puzzle should do) or viewer/controller and figured that sort of thing was happening. In that case, I'll try to get a bunch more Variegation stuff ready.

**Comment by Calamitizer** [comment]
@pickten, I seem to remember you linking a playable version of this hosted somewhere on GitHub, but I can't remember where. Could you remind me?

Also, I've started looking through the source now.

**Comment by pickten** [comment]
https://jsfiddle.net/pickten/jvkngLg6/ is the thing, but it is less up-to-date on some stuff. Specifically, it has a smaller set of prebuilt puzzles (and hence even less diversity), and doesn't have movement. This stuff works fine from the console, though, and it's reasonably easy to play; the one thing you have to note, though, is that just about all functions are pure, including the input function (`doInput`), so you will have to do `p = Molpy.Sokoban.doInput(p,__)` if you use the full version.

**Pull request merged**
