### PR TITLE
Mario fix

### PR DESCRIPTION
**Pull request by Calamitizer**
This is the (final!?) Mario fix. It can't automerge, so let me know if it's better for me to sync with TaT and then re-push, but it doesn't seem like it should conflict much since I don't think pickten worked with IP this push. If he did, let me know and I'll take care of it.

Also I sneaked in a papal boost for the hell of it, let me know if it's not cool. The name pun was too hard to resist.

### CODE REVIEW

**Comment by pickten** [comment]
While I didn't, this was the next thing on my list for the blueness update, so there'll be a couple conflicts in castle.js (though probably *really* easy ones) when that's done.

Also, why is there a big blank space in the middle of Repeatable, where an ASHF checker seems to be?

Anyways, this is good.

**Comment by eternaldensity** [comment]
That was pretty easy.  The conflict was just that both the master and your branch had an extra boost, so it was trivial to remove the conflict markers and have it with your new boost after the other new boost :D

And you ninja'd me!

Hmm, dunno about the blank space, i'll look...

**Comment by eternaldensity** [comment]
I don't see a blank space.  (I'm looking in the code.  Or do you mean on the GUI?)

**Comment by pickten** [comment]
It was one of the changes. Sneaky ninjas (you ninja'd me as well).

**Comment by Calamitizer** [comment]
I do tend to create lots of whitespace to separate code I've c/p'ed from elsewhere for reference, to make sure it gets deleted afterwards. Did I forget to delete the space? =p

**Comment by eternaldensity** [comment]
I'm not seeing it.

**Comment by pickten** [comment]
Removed in one of the changes here, not added in them.

**Pull request merged**
