### PR TITLE
Please tell me there's been no change in the last 20 minutes

### PR DESCRIPTION
**Pull request by pickten**
I rushed to redo this so that it would work. I seriously hope it did. This contains Calamitizer's latest changes (I think), so I believe this should be pulled and not the other.

### CODE REVIEW

**Comment by pickten** [comment]
This contains Calamitizer's latest changes (I think), so I believe this should be pulled and not the other.

**Comment by Calamitizer** [comment]
Can you tell me what I should check before I push so that I don't force you to go through so many hoops? I still don't have a good handle on github

**Comment by pickten** [comment]
I don't know what it is (not very good with github either). Github doesn't seem to like overlap in files edited. Also, if you're talking about the other pull, I included that in this by using your branch when starting to be on the safe side and avoid conflicts again, so if this is pulled, yours might become unusable and vice versa.

**Comment by eternaldensity** [comment]
It is technically possible for me to resolve a merge, but it is potentially tricky and requires me to remember the correct commands and tofigure out how to merge the changes together.  Glad we got it sorted finally.

**Comment by Calamitizer** [comment]
Great. I have also figured out how to actually resync my local repo with merges that aren't mine (last horse crosses the finish line?), so things should go more smoothly.

**Pull request merged**
