### PR TITLE
Tesseract hotfix, + some fluff

### PR DESCRIPTION
**Pull request by Calamitizer**
I took care of (and tested) the Tesseract hotfix. I also coded 3 (Abattoir, Fields' Mettle, & Lifedrain) of the placeholder boosts and a badge.

This update will be version 3.7. I've also changed the version name, if it's alright for me to do that.

### CODE REVIEW

**Comment by pickten** [comment]
Since this will also conflict with my patch, ED, please pull only to master (and do so ASAP), and wait on gh-pages after my patch can be re-added (which should be done within two-three hours after you pull). Also, Calamitizer, you should probably edit the changelog.

**Comment by Calamitizer** [comment]
Sorry, I misunderstood something, I will wait until yours is merged before pushing more. I'm still having a lot of trouble with github but it coming together. 

Editing the changelog seems like a quite reasonable idea, though. =p I'll do it soon.

**Comment by pickten** [comment]
Oh no, this should be merged first. The problem is that github cannot merge mine ATM, and if I edit, it will probably not be compatible with this either, but mine is probably much shorter (in terms of places to change) so it's better that you merge here, I pull to my master, then I make a new branch, edit there, and push to this.

Github can handle multiple pulls at once, but isn't great when the files edited list overlaps.

**Comment by Calamitizer** [comment]
Ah, okay. Well, I'm without a computer for a couple days anyway, so I'll wait for these both to merge and then update my part of the changelog later in the week.

**Comment by eternaldensity** [comment]
Okay this is in. Yay, mayo!

**Comment by pickten** [comment]
OK, actually it's later than I counted on so I'll redo it tomorrow if I have the time. If not, it might be a good week though, because I will also be generally computer-less for about a week.

**Pull request merged**
